project:
  type: book
  output-dir: _book
  resources:
    - CNAME

book:
  title: "Web APIs with R"
  reader-mode: true

  page-footer:
    left: |
      Web APIs with R is being written by Jon Harmon. Join the
      <a href="https://DSLC.io/join">Data Science Learning Community Slack</a> to
      discuss the book!
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  cover-image: cover.png
  favicon: cover.png
  site-url: https://wapir.io/
  repo-url: https://github.com/jonthegeek/wapir/
  repo-branch: main
  repo-actions: [edit, issue]

  chapters:
    - index.qmd
    - intro.qmd

    - part: part-get_started.qmd
      chapters:
        - apis-start.qmd
        - schemas.qmd
        - httr2.qmd
        - authentication.qmd

    - part: part-get_more_data.qmd
      chapters:
        - pagination.qmd
        - rvest.qmd
        - responses.qmd

    - part: part-do_more.qmd
      chapters:
        - httr2-other.qmd
        - apis-find.qmd
        - accessing-other.qmd
        - learn-more.qmd

  appendices:
    - examples-toy.qmd

format:
  html:
    theme:
      - cosmo
    code-link: true
    author-meta: "Jon Harmon"
    callout-appearance: simple

editor: source
