project:
  type: book
  output-dir: _book
  resources:
    - CNAME

book:
  title: "Web APIs with R"
  reader-mode: true

  page-footer:
    left: |
      Web APIs with R is being written by Jon Harmon. Join the
      <a href="https://DSLC.io/join">Data Science Learning Community Slack</a> to
      discuss the book!
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  cover-image: cover.png
  favicon: cover.png
  site-url: https://jonthegeek.github.io/wapir/
  repo-url: https://github.com/jonthegeek/wapir/
  repo-branch: main
  repo-actions: [edit, issue]

  chapters:
    - index.qmd
    - intro.qmd

    - part: part_accessing.qmd
      chapters:
        - apis-start.qmd
        - openapi.qmd
        - httr2.qmd
        - httr2-authentication.qmd
        - httr2-responses.qmd
        - httr2-perform.qmd
        - httr2-methods.qmd
        - apis-find.qmd
        - apis-packages.qmd
        - accessing-other.qmd
        - rvest.qmd
        - accessing-more.qmd

    - part: part_creating.qmd
      chapters:
        - plumber-intro.qmd
        - plumber-input.qmd
        - plumber-output.qmd
        - plumber-errors.qmd
        - plumber-security.qmd
        - plumber-test.qmd
        - plumber-deploy.qmd
        - creating-more.qmd

  appendices:
    - examples-toy.qmd
    - plumber-missing-manual.qmd

format:
  html:
    theme:
      - cosmo
    code-link: true
    author-meta: "Jon Harmon"
    callout-appearance: simple

editor: source
