project:
  type: book
  output-dir: _book

book:
  title: "Web APIs with R"
  reader-mode: true

  page-footer:
    left: |
      Web APIs with R is being written by Jon Harmon. Join the
      <a href="https://r4ds.io/join">R4DS Community Slack</a> to
      discuss the book!
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  cover-image: cover.png
  favicon: cover.png
  site-url: https://jonthegeek.github.io/wapir/
  repo-url: https://github.com/jonthegeek/wapir/
  repo-branch: main
  repo-actions: [edit, issue]

  chapters:
    - index.qmd
    - intro.qmd

    - part: part_accessing.qmd
      chapters:
        - apis.qmd
        - httr2.qmd
        - authentication.qmd
        - responses.qmd
        - perform.qmd
        - find-apis.qmd
        - packages.qmd
        - accessing-other.qmd
        - rvest.qmd
        - accessing-more.qmd

    - part: part_creating.qmd
      chapters:
        - plumber.qmd
        - deploy.qmd
        - test-plumber.qmd
        - creating-more.qmd

  appendices:
    - examples.qmd

format:
  html:
    theme:
      - cosmo
    code-link: true
    author-meta: "Jon Harmon"
    callout-appearance: simple

editor: source
